version: "3.9"
services:
  fake-gcs-server:
    image: fsouza/fake-gcs-server
    command: -backend memory -scheme http -port 8080 -public-host localhost:8081
    ports:
      - 127.0.0.1:8081:8080
  firebase-emulator:
    build:
      context: .
      dockerfile: firebase-emulator.Dockerfile
    ports:
      - 127.0.0.1:9199:9199
      - 127.0.0.1:4000:4000
      - 127.0.0.1:8080:8080
    volumes:
      - ./.firebaserc:/.firebaserc:ro
      - ./firebase.json:/firebase.json:ro
      - ./storage.rules:/storage.rules:ro
